Work on landing page feedback
crane-cloud/frontend pull request #336
Opened 2021-04-21 15:03 UTC by neelxie

#### What does this PR do?
It works on the feedback shared for the landing page

#### Ticket
https://trello.com/c/y3KcgxzL

#### Screenshots

![Screenshot from 2021-04-21 17-57-05](https://user-images.githubusercontent.com/32802973/115576100-d9bc7700-a2cb-11eb-9997-cad7a98ffc30.png)
![Screenshot from 2021-04-21 17-57-57](https://user-images.githubusercontent.com/32802973/115576114-dcb76780-a2cb-11eb-9751-e30cb5ff07fb.png)

2021-04-25 18:26 UTC, Mubangizi submitted a review, later dismissed
LGTM

2021-04-26 21:50 UTC, Mubangizi submitted a review, later dismissed

2021-04-27 11:00 UTC, kawerewagaba requested changes
let's get those changes in. otherwise good job on the restructuring

2021-04-28 10:44 UTC, kawerewagaba approved these changes
lgtm

2021-04-28 10:44 UTC, merged