Fix header for authentication pages
crane-cloud/frontend pull request #342
Opened 2021-05-06 07:38 UTC by neelxie

#### What does this PR do?
It fixes issues with the header in login, password reset and also streamline by making use of CSS module for the component

#### Ticket
https://trello.com/c/zoalRGRO

#### Screenshot

Click the login page, try to hover over the header navigation items like the docs and team

2021-05-06 17:32 UTC, kawerewagaba commented
<img width="1412" alt="Screenshot 2021-05-06 at 20 30 49" src="https://user-images.githubusercontent.com/24539185/117340820-01a20200-aeaa-11eb-8556-22d16bbdf70f.png">
looks like previous changes are not in this pr... make sure to include them

2021-05-06 17:33 UTC, kawerewagaba requested changes
include previous changes

2021-05-06 17:54 UTC, neelxie commented
> <img alt="Screenshot 2021-05-06 at 20 30 49" width="1412" src="https://user-images.githubusercontent.com/24539185/117340820-01a20200-aeaa-11eb-8556-22d16bbdf70f.png">
> 
> looks like previous changes are not in this pr... make sure to include them

@kawerewagaba there's already a PR handling that

2021-05-07 08:40 UTC, kawerewagaba approved these changes

2021-05-07 08:40 UTC, merged