Change location to Data center location
crane-cloud/frontend pull request #364
Opened 2021-07-02 02:23 UTC by neelxie

#### What does this PR do?
It replaces project form location to data center location, this arose as UX feedback from users as they could understand what location meant at Project Creation with the first instinct being that they were being asked for their location.

#### Ticket
https://trello.com/c/mWNF8E4E

#### Screenshots
                                                                 **from**
![Screenshot from 2021-07-02 04-36-02](https://user-images.githubusercontent.com/32802973/124210935-fc9daf80-daf4-11eb-8673-ab6834cd8d60.png)

                                                                 **To**
![Screenshot from 2021-07-02 04-38-01](https://user-images.githubusercontent.com/32802973/124210941-fe677300-daf4-11eb-9739-ba61550c83fd.png)

2021-07-02 09:46 UTC, khalifan-kfan commented
It makes the form more elaborate

2021-07-02 15:55 UTC, rhodinemma commented
That will be more vivid to an end-user.

2021-07-05 16:09 UTC, khalifan-kfan approved these changes

2021-07-06 07:51 UTC, MutegekiHenry approved these changes
Thanks @neelxie for the refactor

2021-07-07 13:42 UTC, kawerewagaba requested changes
can we have it as `Choose data center`

2021-07-07 13:42 UTC, kawerewagaba commented on src/components/UserProjectsPage/index.jsx
> +                placeholder="Choose Datacenter location"
Can we have `Datacenter` in lowercase. Also, do we still need to have `location` there? how about just `data center`?

2021-07-08 18:18 UTC, kawerewagaba approved these changes

2021-07-08 18:18 UTC, merged