Redesign project delete confirmation modal
crane-cloud/frontend pull request #380
Opened 2021-07-22 18:23 UTC by khalifan-kfan

# Description

This adds a provision for users to retype the project name before deleting it. It also removes the persistent error when new text is added

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Trello Ticket ID

https://trello.com/c/osF4aFnV

## How Can This Been Tested?

Pull this branch and run it locally, open and try to delete a project. In the modal fill in the correct project name so as to activate the delete option

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

# Screenshots
How  it was Before
![deleting before](https://user-images.githubusercontent.com/69305400/126689452-fc43997e-1bf9-4849-8abf-920ea9157d4c.png)

Now
Before inputting the  write name, "inactive delete button"
![new delete comfirmation modal](https://user-images.githubusercontent.com/69305400/126689019-6665865b-1721-489f-8bc9-19e72c1d539e.png)
After inputting the  write name, "active delete button"
![delete confirmation2](https://user-images.githubusercontent.com/69305400/126689026-9bcf244c-2f9c-4d39-9c46-9641de59fca5.png)

2021-07-22 18:24 UTC, fel-w approved these changes

2021-07-22 20:28 UTC, StephenAraka requested changes
Good stuff... 
Let's maintain the Cancel button in black
![image](https://user-images.githubusercontent.com/29985169/126705212-d6fbcc56-3dc0-4de0-a9ae-fdc9446a273e.png)

2021-07-22 20:31 UTC, StephenAraka commented
Also, given this new design, I think the 'Note that this is irreversible' can come below the input field.
What do you guys think?

2021-07-23 02:43 UTC, fel-w commented
> Good stuff...
> Let's maintain the Cancel button in black
> ![image](https://user-images.githubusercontent.com/29985169/126705212-d6fbcc56-3dc0-4de0-a9ae-fdc9446a273e.png)

2021-07-23 02:44 UTC, fel-w commented
> Also, given this new design, I think the 'Note that this is irreversible' can come below the input field.
> What do you guys think?

Yeah, it looks much better there

2021-07-23 02:55 UTC, fel-w approved these changes

2021-07-23 05:39 UTC, merged