Ft options section
crane-cloud/frontend pull request #383
Opened 2021-07-26 10:41 UTC by neelxie

# Description

Recreates the database buttons section to align with the new design found here https://www.figma.com/file/eqOJOd4FuJAz9piNtovv9a/Crane-Cloud?node-id=1943%3A0

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Trello Ticket ID
https://trello.com/c/w2hRIj0W

## How Can This Be Tested?
Pull this branch and navigate to a database.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

# Screenshots
![Screenshot from 2021-07-26 13-27-24](https://user-images.githubusercontent.com/32802973/126976059-20278feb-d9a2-4fd9-9053-3e98894e75d9.png)

2021-07-26 11:41 UTC, StephenAraka requested changes
Let's have these in 'not uppercase'. As in the design.
| FROM | TO |
|:-------------:|:-------------:|
|   ![image](https://user-images.githubusercontent.com/29985169/126983382-5c4d8ad0-0cca-4b61-bbde-86c0127f2d5c.png)    | ![image](https://user-images.githubusercontent.com/29985169/126982388-e8492ae9-d296-4550-bd27-98a2638e727a.png) |



And this too maybe? In 'not capitalized'?... e.g. from **Change Password** to **Change password**. As in the design.
| FROM | TO |
|:-------------:|:-------------:|
| ![image](https://user-images.githubusercontent.com/29985169/126983656-e2e564b6-0de9-4b05-94da-e1fbeb143934.png) | ![image](https://user-images.githubusercontent.com/29985169/126982833-4e5991d8-7721-4671-8cb6-85eff2d96466.png) |

2021-07-26 12:08 UTC, neelxie commented
> Let's have these in 'not uppercase'. As in the design.
> 
> FROM	TO
> ![image](https://user-images.githubusercontent.com/29985169/126983382-5c4d8ad0-0cca-4b61-bbde-86c0127f2d5c.png)	![image](https://user-images.githubusercontent.com/29985169/126982388-e8492ae9-d296-4550-bd27-98a2638e727a.png)
> And this too maybe? In 'not capitalized'?... e.g. from **Change Password** to **Change password**. As in the design.
> 
> FROM	TO
> ![image](https://user-images.githubusercontent.com/29985169/126983656-e2e564b6-0de9-4b05-94da-e1fbeb143934.png)	![image](https://user-images.githubusercontent.com/29985169/126982833-4e5991d8-7721-4671-8cb6-85eff2d96466.png)

@StephenAraka this has been integrated.

2021-07-26 12:23 UTC, khalifan-kfan approved these changes

2021-07-29 04:09 UTC, StephenAraka approved these changes

2021-07-29 06:22 UTC, merged