Add landing page tests
crane-cloud/frontend pull request #498
Opened 2022-03-18 03:24 UTC by fel-w

# Description

Adds tests for landing page to increase the coverage

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Trello Ticket ID

https://trello.com/c/z8rxT443

## How Can This Been Tested?
Run tests

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

# Screenshots

2022-03-18 05:13 UTC, neelxie commented on src/components/NewLogo/NewLogo.test.js
> +describe('NewLogo Component', () => {
@fel-w try to be more descriptive describing the parts you are testing, it will fix this issue.

2022-03-18 05:14 UTC, neelxie commented on src/components/LandingPage/LandingPage.test.js
> +const props = {
Change this from props to something like LandingPageProps.

2022-03-18 07:38 UTC, fel-w commented on src/components/NewLogo/NewLogo.test.js
> +describe('NewLogo Component', () => {
Got it, thanks @neelxie

2022-03-18 07:48 UTC, rhodinemma approved these changes
Looks good.

2022-03-18 12:29 UTC, khalifan-kfan approved these changes

2022-04-14 06:54 UTC, e-ian requested changes
@fel-w , there are some merge conflicts to be resolved. Please take a look. ditto on the codeclimate issues, some might require a little refactoring

2022-05-06 03:35 UTC, neelxie approved these changes
Have been able to rebase and fix the failing errors on this, its good!

2022-05-09 09:43 UTC, rhodinemma approved these changes
Thank you for the tests.

2022-05-10 07:49 UTC, merged