Project Collaboration
crane-cloud/frontend pull request #600
Opened 2022-10-28 08:18 UTC by rhodinemma

# Description

- Project owners can invite collaborators to their projects under two roles, such as a member or administrator.
- Project owners can change roles for either collaborators [member/admin]
- Project owners can remove collaborators from their project [member/admin]
- Project [members/admins] can't view project management controls such as [update/delete] project

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Trello Ticket ID

## How Can This Been Tested?

Pull and run this branch locally, then visit the project settings page to see the Membership section.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

# Screenshots

![image](https://user-images.githubusercontent.com/63339234/198539359-f0af7170-5455-4c15-be91-8a9e0751f8ce.png)

2022-11-04 11:57 UTC, neelxie approved these changes
LGTM

2022-11-08 16:31 UTC, khalifan-kfan requested changes
logged in as "fam" but when I click options of another user I added I get remove yourself.
![image](https://user-images.githubusercontent.com/69305400/200620042-aa010b4c-c3b7-4282-9c67-5d11e6767143.png)
2. Also when I remove myself I don't get the redirect effect (to projects page)
3. When changing a user's role and they are already admins, the member option is the only one that should show

2022-11-09 17:25 UTC, neelxie approved these changes
LGTM

2022-11-09 17:28 UTC, khalifan-kfan approved these changes

2022-11-09 17:32 UTC, merged