mo(fix dashbord css)
crane-cloud/frontend pull request #647
Opened 2023-02-13 12:54 UTC by mosesmulumba

# Description

Bring the project , cluster and database cards before the graph cards.
Increase the width of the graph to fit the white-space in the card.

## Trello Ticket ID

https://trello.com/c/ByL8Ju7q

## How Can This Been Tested?

This  can be tested locally by running my upstream branch (fx-dashboard)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

2023-02-13 17:47 UTC, Mubangizi requested changes
Hey, @mosesmulumba great work on this but please update the **title** of this PR to reflect what is being done in it. `mo(fix dashboard CSS)` is not a great way to title a PR. You can read [this](https://blog.pragmaticengineer.com/pull-request-or-diff-best-practices/) to learn more about this.

2023-03-02 00:52 UTC, khalifan-kfan approved these changes
LGTM @mosesmulumba,  thanks for this. Please provide screen shots where possible ;)

2023-03-02 13:36 UTC, mosesmulumba commented
> LGTM @mosesmulumba, thanks for this. Please provide screen shots where possible ;)

I will my boss......

2023-03-02 13:42 UTC, rhodinemma approved these changes
thank you for the adjustment

2023-03-02 13:54 UTC, neelxie approved these changes
LGTM

2023-03-02 13:54 UTC, merged