Fx show hide password
crane-cloud/frontend pull request #659
Opened 2023-03-19 19:42 UTC by Bukirwa99

# Description
The hide /show password feature enables the user to either make their password visible or hidden when logging in or registering an account.

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality

## Trello Ticket ID

https://trello.com/c/9SZQYSnt

## How Can This Been Tested?
Run the branch locally and check the login and register account pages

## Checklist:

- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings
- [x ] Any dependent changes have been merged and published in downstream modules

# Screenshots
![Screenshot 2023-03-19 182222](https://user-images.githubusercontent.com/57665496/226204502-236529b4-819a-4eb7-b671-da294966489f.png)
![Screenshot 2023-03-19 182252](https://user-images.githubusercontent.com/57665496/226204550-203105c9-b2ea-4372-8528-e88593028b5d.png)

Add relevant screenshots incase they are relevant

2023-03-19 23:55 UTC, mosesmulumba approved these changes
Thank's for the work......

2023-03-23 07:57 UTC, neelxie commented on src/pages/AdminLoginPage/AdminLoginPage.css
> +.CopyIcon {
What does this do? You notice you copied code without understanding what it even does?

2023-03-23 07:59 UTC, neelxie commented on src/pages/AdminLoginPage/index.js
> +                  <CopyText onClick={this.passwordOnClick} />
What does this do? how is it even necessary, goes to show you copied code without having an understanding of how it works, please try to understand what is required and then implement

2023-03-23 07:59 UTC, neelxie commented on src/pages/LoginPage/LoginPage.css
> +  height: 2.5rem;
remove this as it makes the password input smaller compared to the other inputs.

2023-03-23 08:01 UTC, neelxie requested changes
You are duplicating alot of code and clearly you copied code, you didn't understand, please revisit your code and remove unnecessary code and ofcourse follow the design.

2023-03-28 13:07 UTC, rhodinemma approved these changes
Thank you for this. @Bukirwa99 
But your PR has conflicts, check them out ASAP.

2023-03-30 20:06 UTC, neelxie approved these changes
LGTM

2023-03-30 20:06 UTC, merged