fix: no database data , dropdown animation
crane-cloud/frontend pull request #776
Opened 2023-11-16 10:40 UTC by mosesmulumba

# Description

Fixing the database return error when no databases created yet.  Apparently the table header was being returned even when it had no information in the table. 
Add animation to the dropdown icon in the header. 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Trello Ticket ID

https://trello.com/c/Vh5z9bvo

https://trello.com/c/fqc3MSUd

## How Can This Been Tested?

Pull the remote branch and test it locally. 

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

2023-11-17 08:57 UTC, neelxie approved these changes
LGTM

2023-11-20 06:06 UTC, mirembe-mariam approved these changes

2023-11-20 14:10 UTC, khalifan-kfan requested changes
Thanks, @mosesmulumba 
This update seems to be affecting the loader on this page though

2023-11-22 14:36 UTC, khalifan-kfan approved these changes
Thanks @mosesmulumba

2023-11-23 12:47 UTC, neelxie approved these changes
LGTM

2023-11-23 12:48 UTC, merged