fx: change the logic for fetching activity logs
crane-cloud/frontend pull request #816
Opened 2024-05-22 19:31 UTC by khalifan-kfan

# Description

This PR is to change the base URL for  activity logs to the new microservice URL

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Trello Ticket ID

https://trello.com/c/Gazjtbbq

## How Can This Been Tested?

Run this application and add the environment variable
```REACT_APP_ACTIVITY_LOGS_API_URL``` that should be the base URL to the new app logger activities

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

2024-05-22 23:25 UTC, Mubangizi commented
Hey Khalifan, let us merge into `microservice` branch not `develop`

2024-05-23 01:05 UTC, Mubangizi requested changes
Great work @khalifan-kfan, maybe a few things to modify

2024-05-23 01:05 UTC, Mubangizi commented on src/apis/userActivityLoggerAxios.js
> +import axios from "axios";
Hey, @khalifan-kfan, instead of creating a new file and creating duplicate code, try to do something I did in the same axios file [here](https://github.com/crane-cloud/frontend/pull/818/files#diff-3b1ad3ad19f985c72e3a08852a582a03e5f275b811d0ffba5c396c306c786419)

2024-05-23 01:05 UTC, Mubangizi commented on src/redux/actions/getUserActivities.js
> +  console.log(ACTIVITY_LOGS_API_URL)
I am not sure if this console logger is needed.

2024-05-23 07:29 UTC, khalifan-kfan commented on src/redux/actions/getUserActivities.js
> +  console.log(ACTIVITY_LOGS_API_URL)
Nice refactor @Mubangizi , this has been added, thank you

2024-05-23 12:04 UTC, Mubangizi approved these changes

2024-05-23 14:31 UTC, Mubangizi approved these changes

2024-05-23 14:44 UTC, merged